service: TangleTrigger
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - s3:*
      Resource:
        - arn:aws:s3:::${env:S3_BUCKET_NAME}
        - arn:aws:s3:::${env:S3_BUCKET_NAME}/*
    - Effect: "Allow"
      Action:
        - sns:Publish
      Resource:
        - ${env:SNS_TOPIC_ARN}

  environment:
    IOTA_URL: ${env:IOTA_URL}
    IOTA_ADDRESS: ${env:IOTA_ADDRESS}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    SNS_TOPIC_NAME: ${env:SNS_TOPIC_NAME}
    SNS_TOPIC_ARN: 
      Ref: TxNotification

functions:
  checkAddress:
    handler: handler.checkAddress
    events:
      - schedule:
          name: shedule-check-address
          description: check the tangle for a given address
          rate: rate(30 minutes)
          enabled: true

resources:
  Resources:
    ExistingTxs:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET_NAME}
    
    TxNotification:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${env:SNS_TOPIC_NAME}
        Subscription:
        - Endpoint: ${env:SNS_EMAIL}
          Protocol: email



